limits:
  history:
    overall: 1000
    short: 72
    long: 0
history:
  storage_file: /var/www/html/rates.txt
notifier:
  check_period: 10m
  notifications:
    - threshold: 3.0
      chat_id: 215566004
